theme = "amberwood"

[editor]
line-number = "relative"
bufferline = "always" # like a tabbar, but clicking doesn't work, switch buffers using gn and gp
shell = ["bash", "-c"] # sh -c by default, messes with SIGUSR1 and some other stuff

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
## replaced file-name with file-absolute-path
left = ["mode", "spinner", "file-absolute-path", "read-only-indicator", "file-modification-indicator"]
## added total-line-numbers
right = ["diagnostics", "selections", "register", "position", "file-encoding", "total-line-numbers"]

[editor.indent-guides]
render = true
character = "▏"

## KEYMAPS #########################

## NORMAL MODE - KEYMAPS ###########
[keys.normal]
D = "goto_line_end" # shift+d, works similar to $
s = ["goto_word"] # similar to leap.nvim
C-d = "kill_to_line_end"

# hot reloads flutter application after save
C-s = [":w", ":run-shell-command if [ $(pgrep flutter) ]; then kill -SIGUSR1 $(pgrep flutter); fi"]

[keys.normal.g]
c = "toggle_comments" # toggle comments on a single line with gc

## SELECT MODE - KEYMAPS ###########
[keys.select]
C-c = ["goto_line_end", "yank_main_selection_to_clipboard"]
U = ["goto_line_end", "switch_case"]

[keys.select.g]
c = "toggle_comments" # toggle comments on selections with gc
